language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5

before_install:
  - java install oraclejdk8

install:
  - java -Xmx32m -version
  - pip install --upgrade setuptools
  - pip install mongo-orchestration
  - sudo wget -O ./elasticsearch.tar.gz https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.0.0-rc1.tar.gz
  - tar -xvf elasticsearch.tar.gz
  - cd elasticsearch-5.0.0-rc1
  - echo 'y' |  bin/elasticsearch-plugin install mapper-attachments

before_script:
  - bin/elasticsearch > temp.txt &
  - sleep 10
  - cd ..
  - mongo-orchestration start

script:
  - python setup.py test

after_script:
  - mongo-orchestration stop
